{% set name = "simpervisor" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cec79e13cdbd6edb04a5c98c1ff8d4bd9713e706c069226909a1ef0e89d393c5

build:
  # trigger 1
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - simpervisor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yuvipanda/simpervisor
  license: BSD-3-Clause
  license_family: BSD
  # Vendoring the license file until the packages include it.
  # xref: https://github.com/yuvipanda/simpervisor/pull/5
  license_file: LICENSE
  summary: Simple async process supervisor
  description: |
    simpervisor provides the SupervisedProcess class that provides async methods start, ready, terminate, and kill to manage it.
  dev_url: https://github.com/yuvipanda/simpervisor
  doc_url: https://github.com/yuvipanda/simpervisor

extra:
  recipe-maintainers:
    - consideratio
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
