{% set name = "simpervisor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simpervisor-{{ version }}.tar.gz
  sha256: 7eb87ca86d5e276976f5bb0290975a05d452c6a7b7f58062daea7d8369c823c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  imports:
    - simpervisor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yuvipanda/simpervisor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple async process supervisor
  description: |
    simpervisor provides the SupervisedProcess class that provides async methods start, ready, terminate, and kill to manage it.
  dev_url: https://github.com/yuvipanda/simpervisor
  doc_url: https://github.com/yuvipanda/simpervisor

extra:
  recipe-maintainers:
    - consideratio
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
