travis:
  secure:
    BINSTAR_TOKEN: dFNvrtE4xPVAixXR6Dw4l+UVM5lekuwd87IYOoWa7rQnWr/dkEytcseI/jO+ACL0zekYPKP4QszwslcGhoy/B2XalwKkrY9rn3LveIjZsOxeUZeKdxH8d4KEXjKI6NNyHFe2qgQy+dx7GqTT+SfoRI61PyY7cGPO1kIThEPhNDkxr0LuAPsJA00Tg+RGbX0Bcsfnbr+zD4i/qvCFSu+JLzhT8P+JIhQXfVZ6BgOS7qodhEqgsftAT5y729GOHoyG/dkMZegyFAs03VvWjOOX07E3CruwErh932o9mWzQRFGuKrHSc6WZMM44gD1uB+iZbj96KS/HcD2R3fEOcZyCtASSiIOsz7qINzMq2R2y3xuKwwV15xVaUcQHCJpl3Nk8URmJxnpZJJdF90nsBowkDhIwELRa4NlI0zfSwF0Az2SvTR1SOLW3ipRvV0Fzk/PUVRbUvS5f2CQPQHRZvkjnJYCEeeuSdjLfnR7tavsOvkJnxCxwddvT8E6fiND9dS/EbUCEzchJQzZ5/fBtiJonegwjTOQepvgOwXj4hME74iKTng03p6xSmnW+nUXYCwvhGbGfnc+az6dI35sHgewsYsKDMGYSP0i6qHZj45pON1AwiZXjYqufA1gaLUvYXT6JmzNnvEa0/hYraJd6KnBun2UwU/g60yrvkGZQtokG9is=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
